### ISSUE TITLE
global vs eslint rule

### ISSUE THREAD

**Issue by dasDaniel** [YogliB/svelte-component-template#10]
It's a bit like splitting hair, but wouldn't defining `/*global document*/` at top of the file be 0.0014% better?

https://github.com/YogliB/svelte-component-template/blob/29f9aa76e9f4cf22efcddfabf6af9e44bbec0e1e/src/main.js#L4

**Comment by YogliB** [comment]
I ended up changing the eslint config file to include global browser variables (Found a reference to the issue [here](https://stackoverflow.com/questions/42377038/error-document-is-not-defined-eslint-react/42377069)).
