### ISSUE TITLE
File name switch ups

### ISSUE THREAD

**Issue by Vehmloewff** [YogliB/svelte-component-template#19]
As one can see, the [files array](https://github.com/YogliB/svelte-component-template/blob/master/package.json#L34-L37) in `package.json` and the [main](https://github.com/YogliB/svelte-component-template/blob/master/package.json#L5) and [module](https://github.com/YogliB/svelte-component-template/blob/master/package.json#L4) fields do not match the [file names](https://github.com/YogliB/svelte-component-template/blob/master/rollup.config.js#L24-L25) specified in `rollup.config.js`.

This leads to an error similar to the following after the package is installed and imported by another project:
```
 Error:  Cannot find module <package>
```

**Comment by YogliB** [comment]
You're right.
Want to fix this? 🙂 (The `rollup.config.js` has it right)
