### ISSUE TITLE
question: improve the doc

### ISSUE THREAD

**Issue by dmitrykurmanov** [YogliB/svelte-component-template#301]
Hello! Thanks for your template, looks great! I think the default svelte template should look something like this.

Could you please think about adding some explanation about the branches ( minimal and monorepo). When should I choose it? Now I am testing the "Regular" one.

**Comment by YogliB** [comment]
How's [that](https://github.com/YogliB/svelte-component-template/blob/master/README.md#features)?

**Comment by dmitrykurmanov** [comment]
@YogliB looks great! Thanks!
