### ISSUE TITLE
compnents.module.js

### ISSUE THREAD

**Issue by dmitrykurmanov** [YogliB/svelte-component-template#302]
Hello! Could you please tell why do we need https://github.com/YogliB/svelte-component-template/blob/master/src/components/components.module.js file ?

If I understand it correctly we can use something like that in the `App.svelte` file:

```js
import MyAwesomeComponent from './components/MyAwesomeComponent.svelte';
```

Should we use components.module.js ?

Thanks

**Comment by YogliB** [comment]
Is [this](https://github.com/YogliB/svelte-component-template/blob/master/FAQ.md) ok?

**Comment by dmitrykurmanov** [comment]
@YogliB yes. Thanks
